# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Cherish-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Cherish-iOS
  pod 'Firebase/Analytics'
  pod 'Firebase/Messaging'
end
